# Generated by Django 4.2rc1 on 2023-05-08 08:36

import Employee.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_no', models.IntegerField(default='')),
                ('Name', models.CharField(default='', max_length=20)),
                ('Address', models.CharField(default='', max_length=50)),
                ('Emp_start_date', models.DateField(blank=True, default='', max_length=20)),
                ('Emp_end_date', models.DateField(default='', max_length=20)),
                ('Image', models.ImageField(blank=True, null=True, upload_to=Employee.models.filepath)),
                ('Status', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_no', models.IntegerField(default='')),
                ('Name', models.CharField(default='', max_length=20)),
                ('Address', models.CharField(default='', max_length=50)),
                ('Emp_start_date', models.DateField(blank=True, default='', max_length=20)),
                ('Emp_end_date', models.DateField(default='', max_length=20)),
                ('Image', models.ImageField(blank=True, null=True, upload_to=Employee.models.filepath)),
                ('Status', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
